import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class MyTheme {
  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF006C50),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFF84F8CD),
    onPrimaryContainer: Color(0xFF002116),
    secondary: Color(0xFF4C6359),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFCEE9DB),
    onSecondaryContainer: Color(0xFF082017),
    tertiary: Color(0xFF3F6375),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFC2E8FD),
    onTertiaryContainer: Color(0xFF001F2A),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFBFDF9),
    onBackground: Color(0xFF191C1A),
    surface: Color(0xFFFBFDF9),
    onSurface: Color(0xFF191C1A),
    surfaceVariant: Color(0xFFDBE5DE),
    onSurfaceVariant: Color(0xFF404944),
    outline: Color(0xFF707974),
    onInverseSurface: Color(0xFFEFF1EE),
    inverseSurface: Color(0xFF2E312F),
    inversePrimary: Color(0xFF66DBB1),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF006C50),
    outlineVariant: Color(0xFFBFC9C2),
    scrim: Color(0xFF000000),
  );

  static const darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF66DBB1),
    onPrimary: Color(0xFF003828),
    primaryContainer: Color(0xFF00513C),
    onPrimaryContainer: Color(0xFF84F8CD),
    secondary: Color(0xFFB3CCBF),
    onSecondary: Color(0xFF1E352C),
    secondaryContainer: Color(0xFF354C42),
    onSecondaryContainer: Color(0xFFCEE9DB),
    tertiary: Color(0xFFA6CCE0),
    onTertiary: Color(0xFF0A3445),
    tertiaryContainer: Color(0xFF264B5C),
    onTertiaryContainer: Color(0xFFC2E8FD),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF191C1A),
    onBackground: Color(0xFFE1E3E0),
    surface: Color(0xFF191C1A),
    onSurface: Color(0xFFE1E3E0),
    surfaceVariant: Color(0xFF404944),
    onSurfaceVariant: Color(0xFFBFC9C2),
    outline: Color(0xFF89938D),
    onInverseSurface: Color(0xFF191C1A),
    inverseSurface: Color(0xFFE1E3E0),
    inversePrimary: Color(0xFF006C50),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF66DBB1),
    outlineVariant: Color(0xFF404944),
    scrim: Color(0xFF000000),
  );

  static final textTheme = TextTheme(
    displayLarge: GoogleFonts.ubuntu(fontSize: 57, letterSpacing: 0),
    displayMedium: GoogleFonts.ubuntu(fontSize: 45, letterSpacing: 0),
    displaySmall: GoogleFonts.ubuntu(fontSize: 36, letterSpacing: 0),
    headlineLarge: GoogleFonts.ubuntu(fontSize: 32, letterSpacing: 0),
    headlineMedium: GoogleFonts.ubuntu(fontSize: 28, letterSpacing: 0),
    headlineSmall: GoogleFonts.ubuntu(fontSize: 24, letterSpacing: 0),
    titleLarge: GoogleFonts.ubuntu(fontSize: 22, letterSpacing: 0),
    titleMedium: GoogleFonts.ubuntu(fontSize: 16, letterSpacing: 0.15),
    titleSmall: GoogleFonts.sourceCodePro(fontSize: 14, letterSpacing: 0.1),
    bodyLarge: GoogleFonts.sourceCodePro(fontSize: 16, letterSpacing: 0.15),
    bodySmall: GoogleFonts.sourceCodePro(fontSize: 12, letterSpacing: 0.4),
  );
}
