import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class MyTheme {
  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF146E00),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFF7EFE5D),
    onPrimaryContainer: Color(0xFF022100),
    secondary: Color(0xFF006D3E),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFF96F7B7),
    onSecondaryContainer: Color(0xFF00210F),
    tertiary: Color(0xFF006C4E),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFF86F8C9),
    onTertiaryContainer: Color(0xFF002115),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFF3FFFA),
    onBackground: Color(0xFF00201A),
    surface: Color(0xFFF3FFFA),
    onSurface: Color(0xFF00201A),
    surfaceVariant: Color(0xFFDFE4D7),
    onSurfaceVariant: Color(0xFF43483F),
    outline: Color(0xFF73796E),
    onInverseSurface: Color(0xFFB7FFEC),
    inverseSurface: Color(0xFF00382E),
    inversePrimary: Color(0xFF61E143),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF146E00),
    outlineVariant: Color(0xFFC3C8BC),
    scrim: Color(0xFF000000),
  );

  static const darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF61E143),
    onPrimary: Color(0xFF063900),
    primaryContainer: Color(0xFF0D5300),
    onPrimaryContainer: Color(0xFF7EFE5D),
    secondary: Color(0xFF7BDA9D),
    onSecondary: Color(0xFF00391E),
    secondaryContainer: Color(0xFF00522D),
    onSecondaryContainer: Color(0xFF96F7B7),
    tertiary: Color(0xFF69DBAE),
    onTertiary: Color(0xFF003827),
    tertiaryContainer: Color(0xFF00513A),
    onTertiaryContainer: Color(0xFF86F8C9),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF00201A),
    onBackground: Color(0xFF79F8DC),
    surface: Color(0xFF00201A),
    onSurface: Color(0xFF79F8DC),
    surfaceVariant: Color(0xFF43483F),
    onSurfaceVariant: Color(0xFFC3C8BC),
    outline: Color(0xFF8D9387),
    onInverseSurface: Color(0xFF00201A),
    inverseSurface: Color(0xFF79F8DC),
    inversePrimary: Color(0xFF146E00),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF61E143),
    outlineVariant: Color(0xFF43483F),
    scrim: Color(0xFF000000),
  );

  static final textTheme = TextTheme(
    displayLarge: GoogleFonts.ubuntu(fontSize: 57, letterSpacing: 0),
    displayMedium: GoogleFonts.ubuntu(fontSize: 45, letterSpacing: 0),
    displaySmall: GoogleFonts.ubuntu(fontSize: 36, letterSpacing: 0),
    headlineLarge: GoogleFonts.ubuntu(fontSize: 32, letterSpacing: 0),
    headlineMedium: GoogleFonts.ubuntu(fontSize: 28, letterSpacing: 0),
    headlineSmall: GoogleFonts.ubuntu(fontSize: 24, letterSpacing: 0),
    titleLarge: GoogleFonts.ubuntu(fontSize: 22, letterSpacing: 0),
    titleMedium: GoogleFonts.ubuntu(fontSize: 16, letterSpacing: 0.15),
    titleSmall: GoogleFonts.sourceCodePro(fontSize: 14, letterSpacing: 0.1),
    bodyLarge: GoogleFonts.sourceCodePro(fontSize: 16, letterSpacing: 0.15),
    bodySmall: GoogleFonts.sourceCodePro(fontSize: 12, letterSpacing: 0.4),
  );
}
